#Steps Specific Configuration
general:
Steps:
  gctsDeploy:
    host: 'http://192.140.0.4:8444'
    client: '100'
    abapCredentialsId: 'ABAPUserPasswordCredentialsId'
    repository: 'Dineshfujitsu-gCTSRepo'
    remoteRepositoryURL: "https://github.com/Dineshfujitsu/Dineshfujitsu-gCTSRepo.git"
    role: 'TARGET'
    vSID: 'S4D'
    branch: 'main'
    commit: 'commit'
    scope: 'scope'
    rollback: false
    configuration:
        dummyconfig: "dummyval"
