#Steps Specific Configuration
general:
Steps:
  gctsDeploy:
    host: 'https://hana4poc.zwtkfpvhnzsehekvcftg5kfdud.rx.internal.cloudapp.net:8444'
    client: '100'
    abapCredentialsId: 'ABAPUserPasswordCredentialsId'
    repository: 'Dineshfujitsu-gCTSRepo'
    remoteRepositoryURL: "https://github.com/Dineshfujitsu/gCTSRepo.git"
    role: 'SOURCE'
    vSID: 'S4D'
    branch: 'main'
    commit: '9cd4553'
    scope: 'CRNTCOMMIT'
    rollback: false
    configuration:
        VCS_AUTOMATIC_PULL: "FALSE"
        VCS_AUTOMATIC_PUSH: "FALSE"
        CLIENT_VCS_LOGLVL: "debug"
