#Steps Specific Configuration
general:
Steps:
  gctsDeploy:
    host: 'https://192.140.0.4:8444'
    client: '100'
    abapCredentialsId: 'ABAPUserPasswordCredentialsId'
    repository: 'Dineshfujitsu-gCTSRepo'
    remoteRepositoryURL: "https://github.com/Dineshfujitsu/gCTSRepo.git"
    role: 'SOURCE'
    vSID: 'S4D'
    branch: 'main'
    scope: 'CRNTCOMMIT'
    rollback: false
    configuration:
        VCS_AUTOMATIC_PULL: "FALSE"
        VCS_AUTOMATIC_PUSH: "FALSE"
        CLIENT_VCS_LOGLVL: "debug"
